# Generated by Django 3.2.5 on 2021-07-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='image',
        ),
    ]
